version: "3.8"

services:
    db:
        image: mysql:8.0
        restart: always
        container_name: mysql
        environment:
            MYSQL_DATABASE: pureofdistance
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    # Service untuk phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    db_data:
